plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.4
  CacheRootDirectory: tmp/rubocop_cache
  Exclude:
    - 'vendor/**/*'
    - 'build/**/*'
    - 'ext/qt_ruby_bridge/qt_ruby_bridge.so'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Naming/PredicateMethod:
  AllowedMethods:
    - on_event
    - on_signal
    - off_event
    - off_signal
