inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-minitest
  - rubocop-rake

# frozen_string_literal: true

AllCops:
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.4
  CacheRootDirectory: tmp/rubocop_cache
  Exclude:
    - 'vendor/**/*'
    - 'build/**/*'
    - 'ext/qt_ruby_bridge/qt_ruby_bridge.so'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120

Naming/PredicateMethod:
  AllowedMethods:
    - on_event
    - on_signal
    - off_event
    - off_signal
